package com.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("rating")
   private java.lang.String rating;
   @org.kie.api.definition.type.Label("vacation")
   private java.lang.Integer vacation;
   @org.kie.api.definition.type.Label("service")
   private java.lang.Integer service;

   @org.kie.api.definition.type.Label(value = "name")
   private java.lang.String name;

   public Employee()
   {
   }

   public java.lang.String getRating()
   {
      return this.rating;
   }

   public void setRating(java.lang.String rating)
   {
      this.rating = rating;
   }

   public java.lang.Integer getVacation()
   {
      return this.vacation;
   }

   public void setVacation(java.lang.Integer vacation)
   {
      this.vacation = vacation;
   }

   public java.lang.Integer getService()
   {
      return this.service;
   }

   public void setService(java.lang.Integer service)
   {
      this.service = service;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Employee(java.lang.String rating, java.lang.Integer vacation,
         java.lang.Integer service, java.lang.String name)
   {
      this.rating = rating;
      this.vacation = vacation;
      this.service = service;
      this.name = name;
   }

}